version: '3.4'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  prometheus:
    image: quay.io/prometheus/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
  alertmanager:
    image: quay.io/prometheus/alertmanager
    container_name: alertmanager
    hostname: alertmanager
    depends_on:
      - web
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager-data:/data
    command: --config.file=/etc/alertmanager/alertmanager.yml --log.level=debug
  prometheus-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    hostname: node-exporter
    ports:
      - 9100:9100
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini